services:
  converter:
    build: .
    image: pob-to-poe2-buildplanner
    container_name: pob-to-poe2
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
